resource "aws_key_pair" "tf_key" {
  key_name   = var.key_pair_name                      # The name of the key pair to be created in AWS
  public_key = tls_private_key.rsa.public_key_openssh # The public key generated by the TLS private key resource
}

resource "tls_private_key" "rsa" {
  algorithm = "RSA" # Specifies that the key will use the RSA algorithm
  rsa_bits  = 4096  # The key length is set to 4096 bits for added security
}

resource "local_file" "tf_key" {
  content  = tls_private_key.rsa.private_key_pem # The private key content to be saved locally
  filename = var.file_name                       # The name of the file where the private key will be saved
}
